In [ ]:
# Хоренко Павло ФІТ 4-8 Варіант 32

In [12]:
# Завдання 1: Створіть одновимірний масив (вектор) з першими 20-ма натуральними числами та виведіть його значення.

# Створення вектору
vector = np.arange(1, 21)
# Виведення значень
vector

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [13]:
# Завдання 2: Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його випадковими натуральними числами та виведіть його значення.

# Створення двовимірного масиву (матриці) розміром 3x3 з випадковими натуральними числами від 1 до 100
matrix = np.random.randint(1, 101, size=(3, 3))
# Виведення значень матриці
matrix

array([[84, 44, 35],
       [41, 68, 68],
       [17, 52, 40]])

In [14]:
# Завдання 3: Створіть масив розміром 5x5, заповніть його випадковими дійсними числами в діапазоні від -1 до 1 та виведіть його значення.

# Створення масиву розміром 5x5 з випадковими дійсними числами в діапазоні від -1 до 1
matrix_5x5 = np.random.uniform(-1, 1, size=(5, 5))

# Виведення значень масиву
matrix_5x5


array([[-0.0317813 , -0.57935364, -0.61098305,  0.85217719,  0.21545516],
       [ 0.51385919, -0.74699866, -0.10891518, -0.35177826, -0.78978866],
       [ 0.830492  ,  0.37377236,  0.05607197,  0.65255727, -0.75331633],
       [-0.66199748, -0.74673952,  0.28666948, -0.576654  , -0.94572036],
       [-0.20568004,  0.12623082, -0.52238152,  0.74759304,  0.79382317]])

In [16]:
# Завдання 4: Створіть масив розміром 5x5, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть середнє значення елементів.

# Створення масиву розміром 5x5 з випадковими дійсними числами в діапазоні від 0 до 1
matrix_5x5_random = np.random.uniform(0, 1, size=(5, 5))

# Обчислення середнього значення елементів масиву
mean_value = np.mean(matrix_5x5_random)

# Виведення середнього значення
mean_value

0.4274648329548607

In [18]:
# Завдання 5: Створіть два одновимірних масиви розміром 5, заповніть їх випадковими цілими
# числами в діапазоні від -10 до 10 та виконайте на них поелементні операції додавання,
# віднімання та множення.

# Створення двох одновимірних масивів розміром 5 з випадковими цілими числами в діапазоні від -10 до 10
array1 = np.random.randint(-10, 11, size=5)
array2 = np.random.randint(-10, 11, size=5)

# Виконання поелементних операцій
addition = array1 + array2
subtraction = array1 - array2
multiplication = array1 * array2

# Виведення результатів
array1, array2, addition, subtraction, multiplication


(array([10, -9, -2,  8,  9]),
 array([-1,  9,  6,  2, -3]),
 array([ 9,  0,  4, 10,  6]),
 array([ 11, -18,  -8,   6,  12]),
 array([-10, -81, -12,  16, -27]))

In [24]:
# Завдання 6: Створіть дві матриці 2x2, заповніть їх довільними дійсними числами від 3 до 10 та знайдіть їх добуток.

# Створення двох матриць 2x2 з довільними дійсними числами в діапазоні від 3 до 10
matrix1 = np.random.uniform(3, 10, size=(2, 2))
matrix2 = np.random.uniform(3, 10, size=(2, 2))

# Обчислення добутку матриць
product = np.dot(matrix1, matrix2)

# Виведення результатів
matrix1, matrix2, product

(array([[3.98814496, 4.32022461],
        [8.20722349, 9.60528353]]),
 array([[6.65416231, 4.18030677],
        [4.84408687, 3.00151272]]),
 array([[ 47.46530716,  29.63887851],
        [101.14102504,  63.13909266]]))

In [25]:
# Завдання 7: Створіть дві матриці розміром 2x3 та 3x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 5 та перемножте їх між собою.

# Створення матриці розміром 2x3 з випадковими цілими числами в діапазоні від 1 до 5
matrix1 = np.random.randint(1, 6, size=(2, 3))

# Створення матриці розміром 3x2 з випадковими цілими числами в діапазоні від 1 до 5
matrix2 = np.random.randint(1, 6, size=(3, 2))

# Перемноження матриць
product = np.dot(matrix1, matrix2)

# Виведення результатів
matrix1, matrix2, product

(array([[5, 2, 3],
        [4, 3, 4]]),
 array([[1, 3],
        [3, 2],
        [4, 3]]),
 array([[23, 28],
        [29, 30]]))

In [27]:
# Завдання 8: Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 12 та знайдіть її обернену матрицю.

# Створення матриці розміром 3x3 з випадковими цілими числами в діапазоні від 1 до 12
matrix = np.random.randint(1, 13, size=(3, 3))

# Обчислення оберненої матриці
inverse_matrix = np.linalg.inv(matrix)

# Виведення результатів
matrix, inverse_matrix

(array([[ 1,  8,  9],
        [12,  1,  5],
        [ 3,  9,  2]]),
 array([[-0.05180723,  0.07831325,  0.0373494 ],
        [-0.01084337, -0.03012048,  0.12409639],
        [ 0.12650602,  0.01807229, -0.11445783]]))

In [28]:
# Завдання 9: Створіть матрицю розміром 4x4, заповніть її випадковими дійсними числами в діапазоні від -8 до 8 та транспонуйте її.

# Створення матриці розміром 4x4 з випадковими дійсними числами в діапазоні від -8 до 8
matrix = np.random.uniform(-8, 8, size=(4, 4))

# Транспонування матриці
transposed_matrix = np.transpose(matrix)

# Виведення результатів
matrix, transposed_matrix

(array([[ 0.83281083, -5.5151059 ,  1.02666123,  2.9923624 ],
        [-7.2800033 ,  4.96570133, -0.3140827 ,  4.31435202],
        [ 6.29802786,  3.92334103,  7.76164392,  7.17926098],
        [-6.32403095,  1.18302822,  4.55652873,  1.84541278]]),
 array([[ 0.83281083, -7.2800033 ,  6.29802786, -6.32403095],
        [-5.5151059 ,  4.96570133,  3.92334103,  1.18302822],
        [ 1.02666123, -0.3140827 ,  7.76164392,  4.55652873],
        [ 2.9923624 ,  4.31435202,  7.17926098,  1.84541278]]))

In [29]:
# Завдання 10: Створіть матрицю розміром 3x4 та вектор розміром 4 x1, заповніть їх випадковими
# цілими числами в діапазоні від 1 до 10 та знайдіть середнє значення елементів матриці.

# Створення матриці розміром 3x4 з випадковими цілими числами в діапазоні від 1 до 10
matrix = np.random.randint(1, 11, size=(3, 4))

# Створення вектору розміром 4x1 з випадковими цілими числами в діапазоні від 1 до 10
vector = np.random.randint(1, 11, size=(4, 1))

# Обчислення середнього значення елементів матриці
mean_value = np.mean(matrix)

# Виведення результатів
matrix, vector, mean_value

(array([[ 9,  6,  9,  4],
        [ 7,  2,  6, 10],
        [ 2,  5,  3,  8]]),
 array([[9],
        [2],
        [5],
        [9]]),
 5.916666666666667)

In [30]:
# Завдання 11: Створіть матрицю розміром 2x3 та вектор розміром 3x1, заповніть матрицю
# випадковими цілими числами в діапазоні від 1 до 10, а вектор - випадковими дійсними
# числами від 0 до 1, і знайдіть добуток матриці на вектор.

# Створення матриці розміром 2x3 з випадковими цілими числами від 1 до 10
matrix = np.random.randint(1, 11, size=(2, 3))

# Створення вектора розміром 3x1 з випадковими дійсними числами від 0 до 1
vector = np.random.random(size=(3, 1))

# Обчислення добутку матриці на вектор
result = np.dot(matrix, vector)

# Виведення результатів
matrix, vector, result

(array([[10,  5,  3],
        [ 4, 10,  8]]),
 array([[0.04724823],
        [0.28813852],
        [0.85535964]]),
 array([[4.47925383],
        [9.91325518]]))

In [31]:
# Завдання 12: Створіть дві матриці розміром 3x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їхню різницю.

# Створення двох матриць розміром 3x3 з випадковими цілими числами від 1 до 10
matrix1 = np.random.randint(1, 11, size=(3, 3))
matrix2 = np.random.randint(1, 11, size=(3, 3))

# Обчислення різниці між матрицями
difference = matrix1 - matrix2

# Виведення результатів
matrix1, matrix2, difference

(array([[5, 9, 3],
        [8, 9, 7],
        [1, 2, 6]]),
 array([[ 7,  4,  4],
        [ 2,  7,  1],
        [ 8, 10,  6]]),
 array([[-2,  5, -1],
        [ 6,  2,  6],
        [-7, -8,  0]]))

In [32]:
# Завдання 13: Створіть дві матриці розміром 3x3, заповніть їх випадковими цілими числами в діапазоні від -5 до 5 та знайдіть їх добуток.

# Створення двох матриць розміром 3x3 з випадковими цілими числами від -5 до 5
matrix1 = np.random.randint(-5, 6, size=(3, 3))
matrix2 = np.random.randint(-5, 6, size=(3, 3))

# Обчислення добутку матриць
product = np.dot(matrix1, matrix2)

# Виведення результатів
matrix1, matrix2, product

(array([[ 2,  1, -3],
        [-3,  3, -1],
        [-4,  4,  0]]),
 array([[ 0,  5, -1],
        [ 1, -1,  1],
        [-1,  0,  3]]),
 array([[  4,   9, -10],
        [  4, -18,   3],
        [  4, -24,   8]]))

In [33]:
# Завдання 14: Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні
# від -5 до 5 та знайдіть суму елементів матриці.

# Створення матриці розміром 3x3 з випадковими цілими числами від -5 до 5
matrix = np.random.randint(-5, 6, size=(3, 3))

# Обчислення суми елементів матриці
sum_elements = np.sum(matrix)

# Виведення результатів
matrix, sum_elements

(array([[ 1,  2,  4],
        [ 5, -5, -4],
        [-2, -4, -5]]),
 -8)

In [34]:
# Завдання 15: Створіть матрицю розміром 4x4, заповніть її випадковими дійсними числами в
# діапазоні від 0 до 1 та знайдіть вектор-стовпчик, що містить добуток елементів кожного рядка матриці.

# Створення матриці розміром 4x4 з випадковими дійсними числами від 0 до 1
matrix = np.random.random(size=(4, 4))

# Обчислення добутку елементів кожного рядка матриці
product_per_row = np.prod(matrix, axis=1)

# Перетворення результату в стовпчиковий вектор
product_vector = product_per_row.reshape(-1, 1)

# Виведення результату
matrix, product_per_row, product_vector

(array([[0.71598516, 0.83677324, 0.74784202, 0.52616741],
        [0.37617084, 0.90967633, 0.80708274, 0.33703106],
        [0.53063833, 0.0135948 , 0.175823  , 0.97255444],
        [0.19905682, 0.79091975, 0.21913423, 0.06205218]]),
 array([0.23574669, 0.09308078, 0.00123356, 0.0021408 ]),
 array([[0.23574669],
        [0.09308078],
        [0.00123356],
        [0.0021408 ]]))

In [36]:
# Висновок:

# В даній роботі були виконані численні завдання з роботи з масивами різного розміру та типів у мові програмування Python.
# Розглянуті завдання охоплюють створення та маніпулювання як одновимірними, так і двовимірними масивами.
# Аналіз цих завдань дозволяє підкреслити важливі аспекти програмування і обробки даних.